server:
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  h2:
    console:
      enabled:  true
      path: /h2
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:employeedb:file=~/employeedb;
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: h2
  application:
    name: employee-rest-api